version: 2
jobs:
  build:
    working_directory: ~/mep
    docker:
      - image: materialsvirtuallab/circle-ci-pmg-py3:0.0.2
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            if [ ! -d "/root/miniconda3/envs/test_env" ]; then conda create --quiet --yes --name test_env python=3.6; fi
            python3 -m venv venv
            source activate test_env
            conda install --quiet --yes numpy scipy matplotlib sympy cython
            conda upgrade --quiet --all
            pip install numpy --upgrade
            pip install --quiet --ignore-installed -r requirements.txt -r requirements-ci.txt

      - run:
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            export MPLBACKEND=Agg
            source activate test_env
            pip install --quiet -e .
            mkdir coverage_reports
            pytest --cov=mep --cov-report html:coverage_reports mep
          no_output_timeout: 3600
      - store_artifacts:
          path: coverage_reports/
          destination: tr1
      - store_test_results:
          path: coverage_reports/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

